/**
 * Open AGPL Strudel Engine Message Protocol Action Types
 */

export const ENGINE_ACTIONS = Object.freeze({
  INIT: 'ENGINE_INIT',
  EVALUATE: 'ENGINE_EVALUATE',
  EVALUATE_ALL: 'ENGINE_EVALUATE_ALL',
  STOP: 'ENGINE_STOP',
  PREVIEW_SOUND: 'ENGINE_PREVIEW_SOUND',
  STOP_PREVIEW: 'ENGINE_STOP_PREVIEW',
  PREVIEW_NOTE: 'ENGINE_PREVIEW_NOTE',
  PREVIEW_DRUM: 'ENGINE_PREVIEW_DRUM',
  SET_CPS: 'ENGINE_SET_CPS',
  SET_PLAY_STATE: 'ENGINE_SET_PLAY_STATE',
  GET_STATUS: 'ENGINE_GET_STATUS',
});

export const ENGINE_EVENTS = Object.freeze({
  READY: 'ENGINE_EVENT_READY',
  STATE_CHANGE: 'ENGINE_EVENT_STATE_CHANGE',
  ERROR: 'ENGINE_EVENT_ERROR',
  PREVIEW_ENDED: 'ENGINE_EVENT_PREVIEW_ENDED',
});
